import type { MatchAnalysis, FrameData } from "./types";

const frames: FrameData[] = [
  {
    frameIndex: 0,
    timestamp: 0,
    possession: "home",
    ballPosition: { x: 18, y: 48 },
    events: [],
    players: [
      { id: "h1", number: 1, team: "home", role: "gk", position: { x: 5, y: 50 }, action: "goalkeeping" },
      { id: "h2", number: 2, team: "home", role: "def", position: { x: 22, y: 18 }, action: "standing" },
      { id: "h3", number: 5, team: "home", role: "def", position: { x: 20, y: 38 }, action: "standing" },
      { id: "h4", number: 6, team: "home", role: "def", position: { x: 20, y: 62 }, action: "standing" },
      { id: "h5", number: 3, team: "home", role: "def", position: { x: 22, y: 82 }, action: "standing" },
      { id: "h6", number: 8, team: "home", role: "mid", position: { x: 40, y: 30 }, action: "running" },
      { id: "h7", number: 4, team: "home", role: "mid", position: { x: 42, y: 52 }, action: "passing" },
      { id: "h8", number: 10, team: "home", role: "mid", position: { x: 40, y: 72 }, action: "running" },
      { id: "h9", number: 7, team: "home", role: "fwd", position: { x: 65, y: 18 }, action: "running" },
      { id: "h10", number: 9, team: "home", role: "fwd", position: { x: 68, y: 50 }, action: "running" },
      { id: "h11", number: 11, team: "home", role: "fwd", position: { x: 62, y: 80 }, action: "running" },
      { id: "a1", number: 1, team: "away", role: "gk", position: { x: 95, y: 50 }, action: "goalkeeping" },
      { id: "a2", number: 2, team: "away", role: "def", position: { x: 78, y: 18 }, action: "standing" },
      { id: "a3", number: 5, team: "away", role: "def", position: { x: 82, y: 38 }, action: "standing" },
      { id: "a4", number: 6, team: "away", role: "def", position: { x: 82, y: 62 }, action: "standing" },
      { id: "a5", number: 3, team: "away", role: "def", position: { x: 78, y: 82 }, action: "standing" },
      { id: "a6", number: 8, team: "away", role: "mid", position: { x: 62, y: 25 }, action: "running" },
      { id: "a7", number: 4, team: "away", role: "mid", position: { x: 58, y: 42 }, action: "standing" },
      { id: "a8", number: 10, team: "away", role: "mid", position: { x: 58, y: 58 }, action: "standing" },
      { id: "a9", number: 7, team: "away", role: "mid", position: { x: 62, y: 75 }, action: "running" },
      { id: "a10", number: 11, team: "away", role: "mid", position: { x: 55, y: 50 }, action: "standing" },
      { id: "a11", number: 9, team: "away", role: "fwd", position: { x: 46, y: 50 }, action: "running" },
    ],
  },
  {
    frameIndex: 1,
    timestamp: 18,
    possession: "home",
    ballPosition: { x: 88, y: 8 },
    events: [
      {
        id: "e1",
        timestamp: 18,
        type: "corner",
        team: "home",
        description: "Corner kick won by Eagles FC after deflection",
        confidence: 0.92,
        isKeyMoment: true,
        position: { x: 100, y: 0 },
      },
    ],
    players: [
      { id: "h1", number: 1, team: "home", role: "gk", position: { x: 5, y: 50 }, action: "goalkeeping" },
      { id: "h2", number: 2, team: "home", role: "def", position: { x: 45, y: 15 }, action: "running" },
      { id: "h3", number: 5, team: "home", role: "def", position: { x: 80, y: 38 }, action: "jumping" },
      { id: "h4", number: 6, team: "home", role: "def", position: { x: 82, y: 55 }, action: "jumping" },
      { id: "h5", number: 3, team: "home", role: "def", position: { x: 40, y: 82 }, action: "standing" },
      { id: "h6", number: 8, team: "home", role: "mid", position: { x: 72, y: 28 }, action: "running" },
      { id: "h7", number: 4, team: "home", role: "mid", position: { x: 55, y: 50 }, action: "standing" },
      { id: "h8", number: 10, team: "home", role: "mid", position: { x: 68, y: 70 }, action: "running" },
      { id: "h9", number: 7, team: "home", role: "fwd", position: { x: 92, y: 8 }, action: "passing" },
      { id: "h10", number: 9, team: "home", role: "fwd", position: { x: 87, y: 45 }, action: "jumping" },
      { id: "h11", number: 11, team: "home", role: "fwd", position: { x: 85, y: 68 }, action: "running" },
      { id: "a1", number: 1, team: "away", role: "gk", position: { x: 92, y: 50 }, action: "goalkeeping" },
      { id: "a2", number: 2, team: "away", role: "def", position: { x: 83, y: 20 }, action: "jumping" },
      { id: "a3", number: 5, team: "away", role: "def", position: { x: 88, y: 40 }, action: "jumping" },
      { id: "a4", number: 6, team: "away", role: "def", position: { x: 88, y: 60 }, action: "standing" },
      { id: "a5", number: 3, team: "away", role: "def", position: { x: 83, y: 80 }, action: "standing" },
      { id: "a6", number: 8, team: "away", role: "mid", position: { x: 75, y: 25 }, action: "running" },
      { id: "a7", number: 4, team: "away", role: "mid", position: { x: 70, y: 42 }, action: "standing" },
      { id: "a8", number: 10, team: "away", role: "mid", position: { x: 70, y: 60 }, action: "standing" },
      { id: "a9", number: 7, team: "away", role: "mid", position: { x: 75, y: 78 }, action: "standing" },
      { id: "a10", number: 11, team: "away", role: "mid", position: { x: 62, y: 50 }, action: "standing" },
      { id: "a11", number: 9, team: "away", role: "fwd", position: { x: 55, y: 50 }, action: "running" },
    ],
  },
  {
    frameIndex: 2,
    timestamp: 42,
    possession: "away",
    ballPosition: { x: 62, y: 55 },
    events: [
      {
        id: "e2",
        timestamp: 42,
        type: "pass",
        team: "away",
        description: "City United #11 plays incisive through-ball — counter-attack developing",
        confidence: 0.88,
        isKeyMoment: true,
        position: { x: 55, y: 50 },
      },
    ],
    players: [
      { id: "h1", number: 1, team: "home", role: "gk", position: { x: 8, y: 50 }, action: "goalkeeping" },
      { id: "h2", number: 2, team: "home", role: "def", position: { x: 32, y: 22 }, action: "running" },
      { id: "h3", number: 5, team: "home", role: "def", position: { x: 28, y: 40 }, action: "running" },
      { id: "h4", number: 6, team: "home", role: "def", position: { x: 28, y: 62 }, action: "running" },
      { id: "h5", number: 3, team: "home", role: "def", position: { x: 30, y: 80 }, action: "running" },
      { id: "h6", number: 8, team: "home", role: "mid", position: { x: 52, y: 32 }, action: "running" },
      { id: "h7", number: 4, team: "home", role: "mid", position: { x: 48, y: 50 }, action: "running" },
      { id: "h8", number: 10, team: "home", role: "mid", position: { x: 50, y: 70 }, action: "running" },
      { id: "h9", number: 7, team: "home", role: "fwd", position: { x: 60, y: 20 }, action: "running" },
      { id: "h10", number: 9, team: "home", role: "fwd", position: { x: 58, y: 48 }, action: "running" },
      { id: "h11", number: 11, team: "home", role: "fwd", position: { x: 55, y: 75 }, action: "running" },
      { id: "a1", number: 1, team: "away", role: "gk", position: { x: 95, y: 50 }, action: "goalkeeping" },
      { id: "a2", number: 2, team: "away", role: "def", position: { x: 72, y: 18 }, action: "standing" },
      { id: "a3", number: 5, team: "away", role: "def", position: { x: 75, y: 38 }, action: "standing" },
      { id: "a4", number: 6, team: "away", role: "def", position: { x: 75, y: 62 }, action: "standing" },
      { id: "a5", number: 3, team: "away", role: "def", position: { x: 72, y: 82 }, action: "standing" },
      { id: "a6", number: 8, team: "away", role: "mid", position: { x: 60, y: 22 }, action: "running" },
      { id: "a7", number: 4, team: "away", role: "mid", position: { x: 58, y: 38 }, action: "running" },
      { id: "a8", number: 10, team: "away", role: "mid", position: { x: 58, y: 62 }, action: "running" },
      { id: "a9", number: 7, team: "away", role: "mid", position: { x: 60, y: 78 }, action: "running" },
      { id: "a10", number: 11, team: "away", role: "mid", position: { x: 55, y: 50 }, action: "passing" },
      { id: "a11", number: 9, team: "away", role: "fwd", position: { x: 42, y: 48 }, action: "running" },
    ],
  },
  {
    frameIndex: 3,
    timestamp: 65,
    possession: "away",
    ballPosition: { x: 12, y: 45 },
    events: [
      {
        id: "e3",
        timestamp: 65,
        type: "shot",
        team: "away",
        description: "City United #9 strikes from 18 yards — powerful shot low to the left corner",
        confidence: 0.95,
        isKeyMoment: true,
        position: { x: 18, y: 45 },
      },
      {
        id: "e4",
        timestamp: 65,
        type: "save",
        team: "home",
        description: "Eagles FC GK makes excellent low save — pushes wide for corner",
        confidence: 0.95,
        isKeyMoment: true,
        position: { x: 5, y: 45 },
      },
    ],
    players: [
      { id: "h1", number: 1, team: "home", role: "gk", position: { x: 5, y: 46 }, action: "goalkeeping" },
      { id: "h2", number: 2, team: "home", role: "def", position: { x: 18, y: 18 }, action: "running" },
      { id: "h3", number: 5, team: "home", role: "def", position: { x: 14, y: 38 }, action: "running" },
      { id: "h4", number: 6, team: "home", role: "def", position: { x: 14, y: 58 }, action: "running" },
      { id: "h5", number: 3, team: "home", role: "def", position: { x: 16, y: 78 }, action: "running" },
      { id: "h6", number: 8, team: "home", role: "mid", position: { x: 30, y: 32 }, action: "running" },
      { id: "h7", number: 4, team: "home", role: "mid", position: { x: 28, y: 50 }, action: "running" },
      { id: "h8", number: 10, team: "home", role: "mid", position: { x: 30, y: 70 }, action: "running" },
      { id: "h9", number: 7, team: "home", role: "fwd", position: { x: 42, y: 22 }, action: "running" },
      { id: "h10", number: 9, team: "home", role: "fwd", position: { x: 40, y: 50 }, action: "running" },
      { id: "h11", number: 11, team: "home", role: "fwd", position: { x: 42, y: 78 }, action: "running" },
      { id: "a1", number: 1, team: "away", role: "gk", position: { x: 95, y: 50 }, action: "goalkeeping" },
      { id: "a2", number: 2, team: "away", role: "def", position: { x: 35, y: 15 }, action: "running" },
      { id: "a3", number: 5, team: "away", role: "def", position: { x: 32, y: 38 }, action: "running" },
      { id: "a4", number: 6, team: "away", role: "def", position: { x: 32, y: 62 }, action: "running" },
      { id: "a5", number: 3, team: "away", role: "def", position: { x: 35, y: 85 }, action: "running" },
      { id: "a6", number: 8, team: "away", role: "mid", position: { x: 22, y: 25 }, action: "running" },
      { id: "a7", number: 4, team: "away", role: "mid", position: { x: 25, y: 42 }, action: "running" },
      { id: "a8", number: 10, team: "away", role: "mid", position: { x: 25, y: 60 }, action: "running" },
      { id: "a9", number: 7, team: "away", role: "mid", position: { x: 20, y: 78 }, action: "running" },
      { id: "a10", number: 11, team: "away", role: "mid", position: { x: 20, y: 38 }, action: "running" },
      { id: "a11", number: 9, team: "away", role: "fwd", position: { x: 12, y: 48 }, action: "shooting" },
    ],
  },
  {
    frameIndex: 4,
    timestamp: 88,
    possession: "home",
    ballPosition: { x: 58, y: 42 },
    events: [
      {
        id: "e5",
        timestamp: 88,
        type: "tackle",
        team: "home",
        description: "Eagles FC #8 wins ball back in midfield with clean sliding tackle",
        confidence: 0.87,
        isKeyMoment: false,
        position: { x: 55, y: 42 },
      },
    ],
    players: [
      { id: "h1", number: 1, team: "home", role: "gk", position: { x: 5, y: 50 }, action: "goalkeeping" },
      { id: "h2", number: 2, team: "home", role: "def", position: { x: 25, y: 20 }, action: "standing" },
      { id: "h3", number: 5, team: "home", role: "def", position: { x: 22, y: 38 }, action: "standing" },
      { id: "h4", number: 6, team: "home", role: "def", position: { x: 22, y: 62 }, action: "standing" },
      { id: "h5", number: 3, team: "home", role: "def", position: { x: 25, y: 80 }, action: "standing" },
      { id: "h6", number: 8, team: "home", role: "mid", position: { x: 55, y: 42 }, action: "tackling" },
      { id: "h7", number: 4, team: "home", role: "mid", position: { x: 50, y: 55 }, action: "running" },
      { id: "h8", number: 10, team: "home", role: "mid", position: { x: 48, y: 72 }, action: "running" },
      { id: "h9", number: 7, team: "home", role: "fwd", position: { x: 68, y: 20 }, action: "running" },
      { id: "h10", number: 9, team: "home", role: "fwd", position: { x: 65, y: 50 }, action: "running" },
      { id: "h11", number: 11, team: "home", role: "fwd", position: { x: 65, y: 78 }, action: "running" },
      { id: "a1", number: 1, team: "away", role: "gk", position: { x: 95, y: 50 }, action: "goalkeeping" },
      { id: "a2", number: 2, team: "away", role: "def", position: { x: 75, y: 18 }, action: "standing" },
      { id: "a3", number: 5, team: "away", role: "def", position: { x: 80, y: 38 }, action: "standing" },
      { id: "a4", number: 6, team: "away", role: "def", position: { x: 80, y: 62 }, action: "standing" },
      { id: "a5", number: 3, team: "away", role: "def", position: { x: 75, y: 82 }, action: "standing" },
      { id: "a6", number: 8, team: "away", role: "mid", position: { x: 62, y: 25 }, action: "running" },
      { id: "a7", number: 4, team: "away", role: "mid", position: { x: 58, y: 40 }, action: "running" },
      { id: "a8", number: 10, team: "away", role: "mid", position: { x: 58, y: 60 }, action: "running" },
      { id: "a9", number: 7, team: "away", role: "mid", position: { x: 62, y: 78 }, action: "running" },
      { id: "a10", number: 11, team: "away", role: "mid", position: { x: 55, y: 50 }, action: "running" },
      { id: "a11", number: 9, team: "away", role: "fwd", position: { x: 45, y: 50 }, action: "running" },
    ],
  },
  {
    frameIndex: 5,
    timestamp: 112,
    possession: "away",
    ballPosition: { x: 42, y: 62 },
    events: [
      {
        id: "e6",
        timestamp: 112,
        type: "foul",
        team: "away",
        description: "City United #4 cynical foul on Eagles FC #7 — yellow card shown",
        confidence: 0.91,
        isKeyMoment: true,
        position: { x: 42, y: 62 },
      },
    ],
    players: [
      { id: "h1", number: 1, team: "home", role: "gk", position: { x: 5, y: 50 }, action: "goalkeeping" },
      { id: "h2", number: 2, team: "home", role: "def", position: { x: 28, y: 20 }, action: "standing" },
      { id: "h3", number: 5, team: "home", role: "def", position: { x: 25, y: 38 }, action: "standing" },
      { id: "h4", number: 6, team: "home", role: "def", position: { x: 25, y: 62 }, action: "standing" },
      { id: "h5", number: 3, team: "home", role: "def", position: { x: 28, y: 82 }, action: "standing" },
      { id: "h6", number: 8, team: "home", role: "mid", position: { x: 48, y: 30 }, action: "running" },
      { id: "h7", number: 4, team: "home", role: "mid", position: { x: 45, y: 52 }, action: "running" },
      { id: "h8", number: 10, team: "home", role: "mid", position: { x: 45, y: 72 }, action: "running" },
      { id: "h9", number: 7, team: "home", role: "fwd", position: { x: 62, y: 18 }, action: "dribbling" },
      { id: "h10", number: 9, team: "home", role: "fwd", position: { x: 60, y: 48 }, action: "running" },
      { id: "h11", number: 11, team: "home", role: "fwd", position: { x: 42, y: 62 }, action: "standing" },
      { id: "a1", number: 1, team: "away", role: "gk", position: { x: 95, y: 50 }, action: "goalkeeping" },
      { id: "a2", number: 2, team: "away", role: "def", position: { x: 72, y: 15 }, action: "standing" },
      { id: "a3", number: 5, team: "away", role: "def", position: { x: 78, y: 38 }, action: "standing" },
      { id: "a4", number: 6, team: "away", role: "def", position: { x: 78, y: 62 }, action: "standing" },
      { id: "a5", number: 3, team: "away", role: "def", position: { x: 72, y: 85 }, action: "standing" },
      { id: "a6", number: 8, team: "away", role: "mid", position: { x: 60, y: 22 }, action: "running" },
      { id: "a7", number: 4, team: "away", role: "mid", position: { x: 42, y: 60 }, action: "tackling" },
      { id: "a8", number: 10, team: "away", role: "mid", position: { x: 58, y: 58 }, action: "running" },
      { id: "a9", number: 7, team: "away", role: "mid", position: { x: 60, y: 80 }, action: "running" },
      { id: "a10", number: 11, team: "away", role: "mid", position: { x: 52, y: 48 }, action: "running" },
      { id: "a11", number: 9, team: "away", role: "fwd", position: { x: 38, y: 50 }, action: "standing" },
    ],
  },
  {
    frameIndex: 6,
    timestamp: 135,
    possession: "home",
    ballPosition: { x: 78, y: 55 },
    events: [
      {
        id: "e7",
        timestamp: 135,
        type: "freekick",
        team: "home",
        description: "Eagles FC awarded dangerous free kick — 22 yards from goal, central position",
        confidence: 0.93,
        isKeyMoment: true,
        position: { x: 78, y: 50 },
      },
    ],
    players: [
      { id: "h1", number: 1, team: "home", role: "gk", position: { x: 5, y: 50 }, action: "goalkeeping" },
      { id: "h2", number: 2, team: "home", role: "def", position: { x: 62, y: 15 }, action: "running" },
      { id: "h3", number: 5, team: "home", role: "def", position: { x: 82, y: 38 }, action: "jumping" },
      { id: "h4", number: 6, team: "home", role: "def", position: { x: 82, y: 55 }, action: "jumping" },
      { id: "h5", number: 3, team: "home", role: "def", position: { x: 62, y: 82 }, action: "running" },
      { id: "h6", number: 8, team: "home", role: "mid", position: { x: 75, y: 28 }, action: "running" },
      { id: "h7", number: 4, team: "home", role: "mid", position: { x: 62, y: 50 }, action: "standing" },
      { id: "h8", number: 10, team: "home", role: "mid", position: { x: 72, y: 72 }, action: "running" },
      { id: "h9", number: 7, team: "home", role: "fwd", position: { x: 88, y: 22 }, action: "running" },
      { id: "h10", number: 9, team: "home", role: "fwd", position: { x: 86, y: 48 }, action: "jumping" },
      { id: "h11", number: 11, team: "home", role: "fwd", position: { x: 78, y: 55 }, action: "passing" },
      { id: "a1", number: 1, team: "away", role: "gk", position: { x: 92, y: 50 }, action: "goalkeeping" },
      { id: "a2", number: 2, team: "away", role: "def", position: { x: 85, y: 20 }, action: "jumping" },
      { id: "a3", number: 5, team: "away", role: "def", position: { x: 88, y: 40 }, action: "jumping" },
      { id: "a4", number: 6, team: "away", role: "def", position: { x: 88, y: 60 }, action: "standing" },
      { id: "a5", number: 3, team: "away", role: "def", position: { x: 85, y: 80 }, action: "standing" },
      { id: "a6", number: 8, team: "away", role: "mid", position: { x: 78, y: 22 }, action: "standing" },
      { id: "a7", number: 4, team: "away", role: "mid", position: { x: 72, y: 42 }, action: "standing" },
      { id: "a8", number: 10, team: "away", role: "mid", position: { x: 72, y: 60 }, action: "standing" },
      { id: "a9", number: 7, team: "away", role: "mid", position: { x: 78, y: 78 }, action: "standing" },
      { id: "a10", number: 11, team: "away", role: "mid", position: { x: 65, y: 50 }, action: "standing" },
      { id: "a11", number: 9, team: "away", role: "fwd", position: { x: 55, y: 50 }, action: "running" },
    ],
  },
  {
    frameIndex: 7,
    timestamp: 165,
    possession: "home",
    ballPosition: { x: 93, y: 45 },
    events: [
      {
        id: "e8",
        timestamp: 165,
        type: "goal",
        team: "home",
        description: "GOAL! Eagles FC #5 powers header into the top corner from the free kick — 1-0!",
        confidence: 0.98,
        isKeyMoment: true,
        position: { x: 95, y: 50 },
      },
    ],
    players: [
      { id: "h1", number: 1, team: "home", role: "gk", position: { x: 5, y: 50 }, action: "goalkeeping" },
      { id: "h2", number: 2, team: "home", role: "def", position: { x: 65, y: 15 }, action: "running" },
      { id: "h3", number: 5, team: "home", role: "def", position: { x: 92, y: 42 }, action: "jumping" },
      { id: "h4", number: 6, team: "home", role: "def", position: { x: 88, y: 58 }, action: "jumping" },
      { id: "h5", number: 3, team: "home", role: "def", position: { x: 65, y: 82 }, action: "running" },
      { id: "h6", number: 8, team: "home", role: "mid", position: { x: 78, y: 30 }, action: "running" },
      { id: "h7", number: 4, team: "home", role: "mid", position: { x: 72, y: 52 }, action: "running" },
      { id: "h8", number: 10, team: "home", role: "mid", position: { x: 75, y: 72 }, action: "running" },
      { id: "h9", number: 7, team: "home", role: "fwd", position: { x: 91, y: 18 }, action: "running" },
      { id: "h10", number: 9, team: "home", role: "fwd", position: { x: 88, y: 45 }, action: "jumping" },
      { id: "h11", number: 11, team: "home", role: "fwd", position: { x: 80, y: 55 }, action: "running" },
      { id: "a1", number: 1, team: "away", role: "gk", position: { x: 95, y: 52 }, action: "goalkeeping" },
      { id: "a2", number: 2, team: "away", role: "def", position: { x: 86, y: 18 }, action: "jumping" },
      { id: "a3", number: 5, team: "away", role: "def", position: { x: 90, y: 38 }, action: "jumping" },
      { id: "a4", number: 6, team: "away", role: "def", position: { x: 90, y: 62 }, action: "jumping" },
      { id: "a5", number: 3, team: "away", role: "def", position: { x: 86, y: 82 }, action: "standing" },
      { id: "a6", number: 8, team: "away", role: "mid", position: { x: 80, y: 22 }, action: "running" },
      { id: "a7", number: 4, team: "away", role: "mid", position: { x: 75, y: 42 }, action: "standing" },
      { id: "a8", number: 10, team: "away", role: "mid", position: { x: 75, y: 62 }, action: "standing" },
      { id: "a9", number: 7, team: "away", role: "mid", position: { x: 80, y: 80 }, action: "running" },
      { id: "a10", number: 11, team: "away", role: "mid", position: { x: 68, y: 50 }, action: "standing" },
      { id: "a11", number: 9, team: "away", role: "fwd", position: { x: 58, y: 50 }, action: "running" },
    ],
  },
];

function buildHeatmap(teamId: "home" | "away", allFrames: FrameData[]): number[][] {
  const grid: number[][] = Array.from({ length: 10 }, () => Array(10).fill(0));
  for (const frame of allFrames) {
    for (const p of frame.players) {
      if (p.team !== teamId) continue;
      const col = Math.min(9, Math.floor(p.position.x / 10));
      const row = Math.min(9, Math.floor(p.position.y / 10));
      grid[row][col]++;
    }
  }
  const max = Math.max(...grid.flat(), 1);
  return grid.map((row) => row.map((v) => +(v / max).toFixed(2)));
}

export const SAMPLE_ANALYSIS: MatchAnalysis = {
  id: "demo-match-001",
  processedAt: new Date().toISOString(),
  videoDuration: 178,
  framesAnalyzed: frames.length,
  score: { home: 1, away: 0 },
  clipGoals: { home: 1, away: 0 },
  processingMethod: "demo",
  homeTeam: {
    id: "home",
    name: "Eagles FC",
    color: "#3b82f6",
    formation: "4-3-3",
    averagePosition: { x: 48, y: 50 },
    stats: {
      possession: 67,
      passes: 45,
      passAccuracy: 84,
      shots: 4,
      shotsOnTarget: 2,
      tackles: 8,
      fouls: 2,
      corners: 2,
      goals: 1,
      distanceCovered: 3420,
    },
    heatmap: buildHeatmap("home", frames),
  },
  awayTeam: {
    id: "away",
    name: "City United",
    color: "#ef4444",
    formation: "4-5-1",
    averagePosition: { x: 68, y: 50 },
    stats: {
      possession: 33,
      passes: 22,
      passAccuracy: 71,
      shots: 1,
      shotsOnTarget: 1,
      tackles: 12,
      fouls: 5,
      corners: 1,
      goals: 0,
      distanceCovered: 2980,
    },
    heatmap: buildHeatmap("away", frames),
  },
  frames,
  keyEvents: frames.flatMap((f) => f.events),
  insights: [
    {
      id: "i1",
      category: "attacking",
      priority: "critical",
      title: "Set-piece delivery is a major weapon",
      observation:
        "Eagles FC created 2 of their 4 shots directly from set pieces, culminating in the match-winning goal at 2:45. The in-swinging delivery from the right flank caused repeated problems.",
      recommendation:
        "Continue investing training time in this routine. Vary the delivery height — mix in-swingers with flick-on targets at the near post to prevent opponents adapting.",
      affectedTeam: "home",
    },
    {
      id: "i2",
      category: "defensive",
      priority: "high",
      title: "City United's aerial weakness at corners",
      observation:
        "City United conceded 3 aerial duels inside their own box during set pieces, leading directly to the conceded goal. Their #6 was consistently second to the ball.",
      recommendation:
        "Reassign zonal markers — put a taller, physically dominant defender on the penalty spot. Add specialist aerial heading drills twice a week.",
      affectedTeam: "away",
    },
    {
      id: "i3",
      category: "tactical",
      priority: "high",
      title: "City United's defensive line is too deep",
      observation:
        "City United's average defensive line sat at x=80 throughout the clip, gifting Eagles FC over 30m of space in behind the midfield. This allowed unchallenged build-up play.",
      recommendation:
        "Push the defensive line up to x=70 when Eagles FC are in their own half. Coordinate with the midfield to compress the space and force more errors.",
      affectedTeam: "away",
    },
    {
      id: "i4",
      category: "possession",
      priority: "medium",
      title: "City United's ball retention drops under pressure",
      observation:
        "Ball retention fell to 71% compared to Eagles FC's 84%. Under pressing situations, City United's central midfielders frequently played the ball backwards or conceded possession.",
      recommendation:
        "Introduce high-pressure rondos and 4v2 drills to improve ball retention under press. Focus on the #4 and #10, who combined for 6 of the 7 misplaced passes.",
      affectedTeam: "away",
    },
    {
      id: "i5",
      category: "physical",
      priority: "medium",
      title: "Eagles FC dominating aerial duels",
      observation:
        "Eagles FC won 7 of 10 aerial contests tracked, a 70% win rate. This advantage is present across all zones of the pitch, not just the set-piece situations.",
      recommendation:
        "Eagles FC should continue targeting the flanks with early crosses. City United needs specific aerial duel training — focus on timing of jump rather than raw physicality.",
      affectedTeam: "both",
    },
  ],
};
